### ISSUE TITLE
More consistent error reporting on new GRPC API

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#385]
From #383 

When a RPC to subscribe() fails, all we get back is a gRPC status code e.g. StatusCode.INVALID_ARGUMENT(3) with details set to "NotFound".
SubscribeResponse does not yet have an Error field which means that only the gRPC error tells us whether something bad happened.
In order to have VISS-compatible error information, I think we would need to have a serialized-as-string Error message behind the 'details' attribute of the gRPC error (see https://github.com/grpc/grpc/tree/master/examples/python/errors).

We need to return "descriptive" error messages as mich as possible, and preferably having VISS/HTTP-style status codes where it makes sense.

It seems it makes sense to give SubscribeResponse an Error field for consistency, but we may also want to check how to make better use gRPC error mechanism

Adding @argerus @romainletendart  to the discussion

**Comment by romainletendart** [comment]
Here are some extra inconsistencies I noticed which could be addressed as part of fixing this issue:
- Set() databroker implementation does not fill in 'error' proto field, only 'errors'.
- Get() databroker implementation wrongly escapes paths within error/errors messages.
- Get() and Set() error message formats are inconsistent for the same kind of error (404).

**Comment by SebastianSchildt** [comment]
Where it makes sense we should use VISS error codes and reasons https://www.w3.org/TR/viss2-transport/#status-codes when we intend to express the same semantic

**Comment by sophokles73** [comment]
Here's another inconsistency:
When getting the current value for an unknown Data Entry (*No.Such.Path*), the databroker's response contains a global error with code 404.
However, when setting the current value for an unknown Data Entry (*No.Such.Path*), the databroker's response contains a Data Entry specific error with code 404 but no global error.

In general, it is quite unclear what kinds of error codes to expect in the response message under what circumstances because the proto file only covers syntax but (almost) no semantics.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
