### ISSUE TITLE
[Data Broker] When does a client receive a message for a value?

### ISSUE THREAD

**Issue by sophokles73** [eclipse/kuksa.val#410]
While reading through the documentation, I was wondering about the behavior of the Data Broker in the context of providers sending updates for unchanged values.

Let's assume that we have a provider that is sending an update for `Vehicle.Powertrain.Transmission.CurrentGear` every 100ms. Most of the time, the value will be same (because we are not constantly shifting gears). Let's also assume that we have a client that has subscribed to the `Vehicle.Powertrain.Transmission.CurrentGear` data point on the broker. Will the client get notifications only when the current gear actually changes or will it get a notification for each update sent by the provider?

**Comment by argerus** [comment]
The simplified answer is that the client will only be notified on changes.

But to give a bit more detail...

This will actually depend on the `ChangeType` specified in the metadata (which in essense can be either `ON_CHANGE` or `CONTINUOUS`). Now, since VSS doesn't have the concept of change type, databroker will default to setting this to `ON_CHANGE` if it's populated with metadata from a generated VSS `.json` file.

**Comment by sophokles73** [comment]
Thanks for the insight. If I am not mistaken, then this property will (usually) be set by a provider which registers the meta data for the data points it will report or it will be configured globally for the Data Broker instance. In any case, it looks like all subscriptions of clients for the data point will behave the same, according to the configured value, right?

I wonder if this shouldn't rather be a property of a client's subscription instead, i.e. a client can choose when establishing the subscription, if it wants to be notified `CONTINUOUS`ly or `ON_CHANGE` only ...

Another question in this context also will be, if a provider's rate of updates would need to be limited in some way in order to prevent the broker from being flooded with unused/useless data ...

**Comment by argerus** [comment]
> Thanks for the insight. If I am not mistaken, then this property will (usually) be set by a provider which registers the meta data for the data points it will report or it will be configured globally for the Data Broker instance. In any case, it looks like all subscriptions of clients for the data point will behave the same, according to the configured value, right?

Yes. And maybe, this property could even be included as part of VSS at some point (not a discussion I know of though).

> I wonder if this shouldn't rather be a property of a client's subscription instead, i.e. a client can choose when establishing the subscription, if it wants to be notified `CONTINUOUS`ly or `ON_CHANGE` only ...

Well that idea has definitely crossed our minds, but after some back and forth I'm not so sure it makes sense.

One argument for _not_ placing this decision in the hands of the subscriber is that this is an inherit property of the signal itself. Some signals change in an "event like" manner, while others are rather "sampled" at a specific rate (1).

To be frank, the ideas underpinning `CONTINUOUS` vs `ON_CHANGE` hasn't been fully developed yet. One things that is still missing is a way for subscribers to set a desired _sampling rate / update frequency_ when they subscribe to a sampled / `CONTINUOUS` signal. And related (to which your other question hints) a way for databroker to inform the providers of the desired update frequency or whether any updates are needed at all (i.e. a control channel). See (2).

Once that gets implemented, I don't see why the client wouldn't _always_ want to provide a desired update frequency for sampled signals, and likewise want to be notified _only_ when event like signals actually change.

I suppose there will be grey zones though, where a sampled signal doesn't change that much... Then I suppose it could make sense to provide a way to only notify clients of actual changes. But I think then we're starting to move into a more "high level API" where it would also make sense to provide things like "only notify me if the sampled signal changes by more than 5% in X minutes" that would live on top of the concept of `CONTINUOUS` vs `ON_CHANGE` for individual signals.

--

(1) Even though `Vehicle.Powertrain.Transmission.CurrentGear` in your example would be coming in over e.g. CAN every 100 ms, it doesn't represent a "sampled" signal conceptually, since it's value only changes based on events, i.e. the gear is changed, or the signal stops being received, which would result in a notification where the value changes to "Unavailable" in databroker.
Sampled signals would be something like `Vehicle.Speed` or location data.

(2) If you look in the `sdv/databroker/v1/types.proto` files, you can see these commented lines which hints at this:
```protobuf
// int32             min_update_hz  = 10; // Only for CONTINUOUS
// int32             max_update_hz = 11; // Only for CONTINUOUS
```

**Comment by sophokles73** [comment]
Thanks for the detailed explanation :-)

> I think the the distinction between CONTINUOUS and ON_CHANGE as currently specified is an inherit property for the signals in the communication between the databroker and the providers. This will in some ways reflect how the client can subscribe to the different types. But you are right that it could make sense to provide more ways for clients to specify how the want to be notified.

Based on that one could also argue that it is (also) the responsibility of the provider to implement reasonable means to prevent flooding the Data Broker with unneeded data. For example, the provider of the `Vehicle.Powertrain.Transmission.CurrentGear` data point could indeed send an update to the broker only if its value actually changes. We seem to agree that other data points whose values resemble a continuous function would better be sampled at a given frequency.
