### ISSUE TITLE
[Question] GRPC shutdown on closing databroker

### ISSUE THREAD

**Issue by AkhilTThomas** [eclipse/kuksa.val#417]
A small doubt regarding the databroker. Does it send a GRPC SHUTDOWN signal if I close the databroker.
 
I’m monitoring my custom feeder for connectivity change and it does not give me a SHUTDOWN when I terminate the attached databroker, the channel state just changes to IDLE state.

**Comment by argerus** [comment]
> I’m monitoring my custom feeder for connectivity change and it does not give me a SHUTDOWN when I terminate the attached databroker, the channel state just changes to IDLE state.

The channel concept in GRPC can be a little confusing. Internally, the channel implementation is free to open and close connections and transparently reconnect to a service on demand. I don't think a channel will ever go into `SHUTDOWN` state just because a service is temporarily unavailable. See [gRPC Connectivity Semantics and API ](https://grpc.github.io/grpc/cpp/md_doc_connectivity-semantics-and-api.html)

> Does it send a GRPC SHUTDOWN signal if I close the databroker.

I don't think there is such a thing as sending a GRPC SHUTDOWN signal. The databroker *will* close any open streams on shutdown though.

I don't fully know the details, but from what I understand you need to have a RPC context in order to detect that a server/client goes away. I.e. there needs to be an open RPC stream, or you need to be making a (new) unary RPC call in order to detect it.

Just having a channel doesn't give you that information.

**Comment by AkhilTThomas** [comment]
Is there a recommendation for monitoring the loss of connectivity from the broker?
My use case is that I'm getting a continuous flow of information which has to be updated to the broker. So in case the connection fails my update will also fail.
Any callback or event immediately on link fail would be helpful

**Comment by AkhilTThomas** [comment]
I'm using the UpdateDatapoints method currently. 
Thank you for the reply. I will try out the stream API
