### ISSUE TITLE
setValue does not check min/max

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#46]
Currently, I have the following observation: 

```
VSS Client> getMetaData Vehicle.Speed
{
    "action": "getMetaData",
    "metadata": {
        "Vehicle": {
            "children": {
                "Speed": {
                    "datatype": "int32",
                    "description": "Vehicle speed, as sensed by the gearbox.",
                    "max": 250,
                    "min": -250,
                    "type": "sensor",
                    "unit": "km/h",
                    "uuid": "1efc9a11943b5a15ac159786051c5836"
                }
            },
            "description": "High-level vehicle data.",
            "type": "branch",
            "uuid": "1c72453e738511e9b29ad46a6a4b77e9"
        }
    },
    "requestId": "1236",
    "timestamp": 1599086861
}
VSS Client> setValue Vehicle.Speed 366
{
    "action": "set",
    "requestId": "1235",
    "timestamp": 1599087046
}
VSS Client> getValue Vehicle.Speed 
{
    "action": "get",
    "path": "Vehicle.Speed",
    "requestId": "1234",
    "timestamp": 1599087196,
    "value": "366"
}
```
But I do not expect the `setValue  Vehicle.Speed 366` can be successful, because the defined max value is 250.

**Comment by SebastianSchildt** [comment]
The observation is correct, currently the min, max are ignored. I am not sure what we want here in the short term, as not all limit(as in speed) in the core data model make sense. If it is a "general" limitation for all land vehicles it shoudl be more like 600, but how useful it is? Mire useful would be the max of the current vehicle, but that would be a matter of a concrete deployment of the data model.

We might track what Genivi is doing here, a related discussion is https://github.com/GENIVI/vehicle_signal_specification/issues/166

But let's keep this open, because we should do "something" with min/max eventually
