### ISSUE TITLE
Include directory error

### ISSUE THREAD

**Issue by junh-ki** [eclipse/kuksa.val#57]
While building the latest version, I've found out that some directories are inconsistent, therefore making errors.

After including the `jsoncons` library to the `include` directory as below:

`$ sudo cp -R jsoncons-x.xxx.x/include/* /usr/include/`

It makes sense to change `jsonpath` directories from `kuksa.val/src/SubscriptionHandler.cpp`, `kuksa.val/src/VssDatabase.cpp` and `kuksa.val/src/main.cpp` as below:

`#include <jsonpath/json_query.hpp>`   =>   `#include <jsoncons_ext/jsonpath/json_query.hpp>`

This way, building was successful.

**Comment by SebastianSchildt** [comment]
Hi, maybe something did not work for you, when you just did a git pull, because we changed from including jsonscons directly, to using a submodule.

Can you try checking out a new working copy, ether with
`git clone —recursive`

Or a normal`git clone ` followed by `git submodule update —init’

If problem still persists, maybe @wenwenchenbosch can take a look

**Comment by junh-ki** [comment]
> Hi, maybe something did not work for you, when you just did a git pull, because we changed from including jsonscons directly, to using a submodule.
> 
> Can you try checking out a new working copy, ether with
> `git clone —recursive`
> 
> Or a normal`git clone ` followed by `git submodule update —init’
> 
> If problem still persists, maybe @wenwenchenbosch can take a look

I missed the `--recursive` part.
Thank you.
This issue can be closed :)
