### ISSUE TITLE
Shall we introduce dependabot for managing dependencies

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#595]
As of today we do not have a dependabot.yml file for managing dependencies. (This can be compared to kuksa.val.services, which have [one](https://github.com/eclipse/kuksa.val.services/blob/main/.github/dependabot.yml)). A dependabot file could help us to stay up to date by automatically creating pull requests. On the other hand, changing versions mean that regressions may be introduced.

I think we need to:

- Decide what policy we want to have for dependencies. Do we by default want to keep them unchanged unless we need new features or need to update due to security issues, or do we by default want to use "latest and greatest".
- If we want to use "latest and greatest"; decide on how to handles updates. Are we happy to merge PRs where CI pass without manual test, i.e. handle regressions (if any) later when detected?
- If we by some reason want to ignore certain proposals or should have a process for documenting why. Like wiki? "We use version 1.5 of XXX as significant refactoring would be needed to support version 1.6"
- If we want to use Dependabot, agree on how prioritized it shall be to solve/refactor/close the proposals. In general I think it looks bad if they stay open for multiple weeks.

Some tests performed in a fork, showing example pull requests created.

https://github.com/erikbosch/kuksa.val/blob/master/.github/dependabot.yml
https://github.com/erikbosch/kuksa.val/pulls

**Comment by SebastianSchildt** [comment]
My 2 ct
 - Definitely update everything related security asap.
 - I think for components, where we lock dependencies (rust/cargo , python/pipfile.in) we should update regularly (weekly?) and accept merge if CI is green. If that breaks something, our CI sucks. Normally the major(ly) version is fixed in the input file, so if the upstream projects version correctly (something we should do one day as well....), no breakage should happen
 - Not sure dependabot, as I am not sure it can be told to only update minor versions, or versions in line with the master files? And even if, I think instead of updating 23 dependencies individually, you proobably would do one cargo update, updating everything, and check it it again (as we assumed "CI green is enough", you do not really win anything, doing this in multiple steps)

**Comment by erikbosch** [comment]
It seems that we need a bigger discussion on what versions we want to use. An example can be seen in https://github.com/eclipse/kuksa.val.services/pull/80 where dependabot suggest us using a different Linux version in the Docker container. Taking that as an example some guidelines would be good, like:

- What should be our default choice. For Linux in Docker containers and CI a possible approach could be to use latest Ubuntu LTS, and if we by some reason do not want that write and document a good rationale. Another approach could be to agree that for example Ubuntu 20.04 LTS is the preferred choice as not that many has adapted the newest LTS, but then we should not use 22.04 anywhere.
