### ISSUE TITLE
Missing license file in kuksa-client PyPI package since 0.4.0a3

### ISSUE THREAD

**Issue by d-s-e** [eclipse/kuksa.val#612]
The license file is in the PyPI package was included until 0.4.0a2, after that it is missing.

How/Where are the PyPI packages actually created/uploaded? I can't find any reference in the repo, also no version numbers 0.4*.

**Comment by erikbosch** [comment]
As of now we have no automated build flow for the kuksa-client PyPI packages, they are built manually as described in https://github.com/eclipse/kuksa.val/wiki/Release-Process. For the Alpha-releases I have just created tags locally. There have been two reasons for that - one is that the source has not always been a commit on master, it has been created to verify that the PyPI package content is usable for kuksa client relying on the package. The second reason is that by uploading a tag it could give the impression that the tag denotes an alpha release for all components (Databroker, Server, Python client, go client, ...) in this repository, and it could also trigger that we create tagged Docker containers for other components in this repository. So a bigger discussion might be needed (FYI: @SebastianSchildt )

Concerning the license file - I am not aware of any deliberate changes but I will investigate it.

**Comment by erikbosch** [comment]
It turned out the missing license file was due to a cleanup where the file kuksa-client/LICENSE was removed as it was thought to be not necessary, as we have an identical file on repository top level. Unfortunately it was required by `setup.cfg`, but if it cannot find the file it gives no warnings/errors. A PR created in #613 that solves the problem  by using a symbolic link.
