### ISSUE TITLE
KUKSA Server Deprecation?

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#737]
There has not been any active development for KUKSA Server (the C++ server in https://github.com/eclipse/kuksa.val/tree/master/kuksa-val-server) for a long time, apart from integrating newer VSS version and occasional dependency updates. There also generally seems to be limited interest in it.

By that reason I suggest

- That we deprecate KUKSA Server
  - Practically this would mean that we update documentation and also give a warning log printout when starting KUKSA Server
  - Under the deprecation period we may still update KUKSA Server
- That we specify an End-Of-Life date for KUKSA Server, possibly 2024-12-31
  - Meaning that we will not accept any pull requests or issues after that date
  - That we will not fix security issues after that date.

If someone has interest in or use KUKSA Server this will give them 10 months to either migrate to KUKSA Databroker or to step forward and offer continued maintenance of it.

**Comment by SebastianSchildt** [comment]
I think "eventually" (personally I feel rather earlier than later) we should deprecate (well in fact "it is", but clearly stating o in Docs and on startup), and then potentially archive it.

I think, independent from the discussion when and how this exaxtly happens, we should break datbaroker out of here and migrate to its own repository. We planned that for a long time but so far focussed on the "easy" targets like providers. The point is, once datbaroker is "out", we can modify the docs in the new location to not even mention the val-server and differences. Because that regularly leads to confusion of people wanting to use databroker.
