### ISSUE TITLE
Message timestamps are in seconds instead of milliseconds

### ISSUE THREAD

**Issue by mariaivanova-git** [eclipse/kuksa.val#88]
Vehicle Service Specification states that message timestamps should be in milliseconds:

> timestamp | integer | The Coordinated Universal Time (UTC) time that the server returned the response (expressed as number of milliseconds).

while what is actually received from Kuksa Val is in seconds, e.g.: 
```
{
  "action": "subscribe",
  "subscriptionId": 1169547907,
  "timestamp": 1610712309,
  "value": 8204,
  "path": "Vehicle.Drivetrain.FuelSystem.TimeSinceStart"
}
```
So, when there is a big flow of events some of them get overlapping timestamps and cause issues in their proper ordering.

**Comment by wenwenchenbosch** [comment]
Thanks very much for the issue report :+1: 
I will work on it soon to fix it.

**Comment by SebastianSchildt** [comment]
@mariaivanova-git  The timestamps should be fixed in latest master builds. Get a prebuilt docker e.g. here https://ci.eclipse.org/kuksa/job/kuksa.val/job/master/39/

Maybe you can check, if it works as expected (I _expect_ master still be compatible with  0.1.6, in case there is any trouble, please open an Issue)

On thing we need to think about is when you need this in a release. Master has already quite substantial changes but is maybe 1-2 months before release of 0.2.   We could theoretically backport it to 0.1.6, but it is not super trivial (either also needs extensive unittest changes, or loosing the ability for meaning full unittest on 0.1.x branch). Any opinion @chheis

Anyway, first step: Please check if master solves your problem :)

**Comment by mariaivanova-git** [comment]
@wenwenchenbosch and @SebastianSchildt Thank you for fixing the timestamp issue. I've tried out builds e91691c and 863db65 and it works for us.
